"""Generate conformance/adr-vectors.json: fixed inputs and the outputs both SDKs must reproduce.

Ed25519 signatures are deterministic, so a fixed private key yields fixed signatures. Re-run only
when the spec changes: python scripts/gen_adr_vectors.py
"""

import hashlib
import json
from pathlib import Path

from warrant.hashing import canonical_json, content_hash, record_hash, salted_hash
from warrant.merkle import consistency_proof, inclusion_proof, root
from warrant.signing import CHECKPOINT_CONTEXT, SEAL_CONTEXT, SigningKey, seal_message

OUT = Path(__file__).resolve().parents[1] / "conformance" / "adr-vectors.json"

key = SigningKey("vector-issuer", bytes(range(32)))
salt = bytes.fromhex("11" * 32)
contents = [{"hits": 0}, "ABCDE1234F", {"turnover_band": "4-5 crore", "gstin": "29ABCDE1234F1Z5"}, {"n": 1.5, "ok": True, "items": [3, 2, 1]}]
record = {
    "record_id": "01K5A3Q7Z2XV8M9N4B6C1D0001", "record_type": "decision", "tenant": "vector-issuer",
    "stream": "lending", "timestamp": "2026-09-27T10:00:00.000Z", "schema_version": "0", "origin": "live",
    "sequence": 1, "actor": {"name": "credit-agent", "version": "1"},
    "decision": {"class": "credit.approve", "action": "approve", "subject": "LN-1", "status": "acted"},
    "mandate": {"result": "allow"},
}
h = record_hash(record, None)
entries = [hashlib.sha256(bytes([i])).hexdigest() for i in range(11)]
leaves = [bytes.fromhex(e) for e in entries]

vectors = {
    "spec": "adr/0.2",
    "note": "Generated by scripts/gen_adr_vectors.py from the Python reference implementation.",
    "key": {"issuer": key.issuer, "private_key_hex": bytes(range(32)).hex(), "public_key_b64": key.public.to_dict()["public_key"], "key_id": key.key_id},
    "salted": [{"content": c, "salt_hex": salt.hex(), "plain": content_hash(c), "salted": salted_hash(c, salt)} for c in contents],
    "seal": {"record": record, "hash": h, "message": (SEAL_CONTEXT + h.encode()).decode(), "signature": key.sign(SEAL_CONTEXT + h.encode())},
    "seal_sealed_at": {"hash": h, "sealed_at": "2026-09-27T12:00:00.000Z",
                       "message": seal_message(h, "2026-09-27T12:00:00.000Z").decode(),
                       "signature": key.sign(seal_message(h, "2026-09-27T12:00:00.000Z"))},
    "checkpoint_message": {"body": {"spec": "adr/0.2", "kind": "checkpoint", "tree_size": 3, "root": "ab" * 32},
                           "message": (CHECKPOINT_CONTEXT + canonical_json({"spec": "adr/0.2", "kind": "checkpoint", "tree_size": 3, "root": "ab" * 32}).encode()).decode()},
    "merkle": {
        "entries": entries,
        "roots": {str(n): root(leaves[:n]).hex() for n in range(0, len(leaves) + 1)},
        "inclusion": [{"index": i, "size": n, "proof": [p.hex() for p in inclusion_proof(i, leaves[:n])]} for n in (1, 5, 8, 11) for i in range(n)],
        "consistency": [{"from": m, "to": n, "proof": [p.hex() for p in consistency_proof(m, leaves[:n])]} for n in (2, 5, 8, 11) for m in range(1, n + 1)],
    },
}
OUT.write_text(json.dumps(vectors, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
print(f"wrote {OUT}")
